version: '3.7'

services:
  timescaledb:
    image: usertestx10/timescaledb
    container_name: timescaledb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d/

  golang:
    image: golang
    container_name: golang
    working_dir: /app
    depends_on:
      - timescaledb

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - timescaledb

networks:
  by_x10: